### ISSUE TITLE
Optimize bytestring primitive reads

### ISSUE THREAD

**Issue by amannocci** [amannocci/streamy#94]
##### Describe the feature
Optimize bytestring primitives reads to avoid string allocation.

**Comment by plokhotnyuk** [comment]
Hi, Adrien!

I've found your repository by accident when looking for the implementation of the Ryu algorithm for serialization of floating-point primitives through GitHub. Then when browsing your repository I was interested in the JSON package.

Probably you would be interested to look into the code of the [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) library where all primitives are parsed immediately from byte arrays or `java.nio.ByteBuffer` to values efficiently without any allocations.

Feel free to reuse it or just copysome suitable tricks. In any case, your feedback will be greatly appreciated!

**Comment by amannocci** [comment]
Hey !

I already look into your project and I loved it.
I planned to use some tricks like SWAR to do the parsing in Json package and also in other place like the syslog plugin maybe.
I tried to do a kind of abstract parser like [parboiled]() but using another approach.
I also look to this project [borer](https://github.com/sirthias/borer).
I will probably change the parser in a two phase parsing strategy.
By the way, great to talk with you, I appreciate your work :)
